Fixing workflow #2

diff --git a/.github/workflows/djangoapp.yml b/.github/workflows/djangoapp.yml
--- a/.github/workflows/djangoapp.yml
+++ b/.github/workflows/djangoapp.yml
@@ -36,19 +36,24 @@ jobs:
       run: |
         if [[ $(sudo mysql -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='$DB_NAME'" | grep $DB_NAME | wc -l) -eq 0 ]]; then
           echo "Database does not exist, creating"
-          sudo mysql -e "CREATE DATABASE $DB_NAME;"
+          if ! sudo mysql -e "CREATE DATABASE $DB_NAME;"; then
+            echo "Failed to create the database"
+            exit 1
+          fi
         else
           echo "Database already exists, skipping creation"
         fi
-        sudo mysql -e "SELECT User FROM mysql.user WHERE User='$DB_USER'" | grep $DB_USER
-        if [ $? -eq 0 ]
-        then
-          echo "User already exists, skipping creation"
-        else
+    
+        if ! sudo mysql -e "SELECT User FROM mysql.user WHERE User='$DB_USER'" | grep $DB_USER; then
           echo "User does not exist, creating"
-          sudo mysql -e "CREATE USER $DB_USER@localhost IDENTIFIED BY '$DB_PASSWORD';"
+          if ! sudo mysql -e "CREATE USER $DB_USER@localhost IDENTIFIED BY '$DB_PASSWORD';"; then
+            echo "Failed to create the user"
+            exit 1
+          fi
           sudo mysql -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO $DB_USER@localhost;"
           sudo mysql -e "FLUSH PRIVILEGES;"
+        else
+          echo "User already exists, skipping creation"
         fi
       env:
         DB_NAME: ${{ secrets.DB_NAME }}
